# Generated by Django 5.2.5 on 2025-08-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='grade',
            field=models.CharField(choices=[('Grade9', 'Grade 9'), ('Grade10', 'Grade 10'), ('Grade11', 'Grade 11'), ('Grade12', 'Grade 12')], default='Grade9', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='subject',
            field=models.CharField(choices=[('Math', 'Math'), ('English', 'English'), ('Science', 'Science'), ('History', 'History'), ('Computer', 'Computer')], default='Math', max_length=50),
        ),
    ]
