# Generated by Django 5.2.5 on 2025-08-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_commonbook_alter_uploadedfile_subject_quiz_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonbook',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English')], max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('English', 'English')], default='Maths', max_length=50),
        ),
    ]
