# Generated by Django 5.2.5 on 2025-08-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='StudyStreak',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
